### ISSUE TITLE
Can't set netmask to 255.0.0.0 in SoftAP Mode

### ISSUE THREAD

**Issue by Sine-Audio** [mtongnz/ESP8266_ArtNetNode_DMX#2]
When trying to set a WiFi.softAPConfig it's not possible to set 255.0.0.0 as netmask. The DHCP server still gives out 255.255.255.0 as the netmask. Probably an issue with the Arduino library as it's described in [this link](https://github.com/esp8266/Arduino/issues/2578).

**Comment by mtongnz** [comment]
It is a limitation of the ESP core. I have raised the issue on their git (the link you supplied) but haven't heard back yet. 
The subnet is hard coded into the dhcp server code. Hopefully it will be addressed shortly.

**Comment by Sine-Audio** [comment]
Oops! Sorry for stating the obvious then. Didn't read the name, my fault. Hope it will be resolved indeed.

**Comment by mtongnz** [comment]
No problems. I ran into that issue when trying to get the hotspot to receive Artnet. I wasted many hours on it until I finally found that the values are hard coded.
It is possible to set the subnet of the ESP but the dhcp server will only give out 255.255.255.0 so you have to manually configure it on your PC

**Comment by mtongnz** [comment]
Issue is fixed in v1.1.0 but requires modification of lwIP to compile. I have a commit waiting to be merged into the Arduino core to fix this.
See the readme in the 1.1.0 tree for details
